

[[redirects]]
  from = "/teaching"
  to = "/"

[[redirects]]
  from = "/publications"
  to = "/"

[[redirects]]
  from = "/activities"
  to = "/"

[[redirects]]
  from = "/projects"
  to = "/"

[[redirects]]
  from = "/contact"
  to = "/"
